namespace QuestionableCompanion.Models;

public enum LANMessageType
{
	DISCOVER_REQUEST,
	DISCOVER_RESPONSE,
	REQUEST_HELPER,
	HELPER_STATUS,
	INVITE_NOTIFICATION,
	REQUEST_PARTY_INVITE,
	INVITE_ACCEPTED,
	HELPER_IN_PARTY,
	HELPER_READY,
	HELPER_IN_DUTY,
	DUTY_COMPLETE,
	FOLLOW_COMMAND,
	FOLLOW_STARTED,
	FOLLOW_ARRIVED,
	CHAUFFEUR_PICKUP_REQUEST,
	CHAUFFEUR_READY_FOR_PICKUP,
	CHAUFFEUR_HELPER_READY_FOR_MOUNT,
	CHAUFFEUR_HELPER_ARRIVED_DEST,
	CHAUFFEUR_ABORTED,
	CHAUFFEUR_PASSENGER_MOUNTED,
	ERROR,
	DISCONNECT,
	HEARTBEAT
}
